### ISSUE TITLE
Configuration does not accept symbols

### ISSUE THREAD

**Issue by texaco** [death/ssh-tunnels#19]
The configuration variable `ssh-tunnels-configurations` does not accept symbols. This can be useful to parameterize whenever the user have tons of tunnels to configure.

For instance:

```elisp
(use-package ssh-tunnels :ensure t
  :config
  (setq ahost "localhost" alogin "mytunnelserver")
  (setq ssh-tunnels-configurations
        '((:name "sometunnel" :local-port  8080 :remote-port  8080 :host ahost :login alogin))))
```

This configuration turns out on the following error:

    Debugger entered--Lisp error: (wrong-type-argument stringp alogin)
      call-process("ssh" nil t nil "-S" "sometunnel" "-O" "check" alogin)
      apply(call-process "ssh" nil t nil "-S" "sometunnel" ("-O" "check" alogin))

In case it is a feature that fits the package style and philosophy, it can be implemented checking whether the parameter (`:login` in this case) is a string within `ssh-tunnels--command` function. Other wise `eval` it.

```elisp
  (defun ssh-tunnels--command (tunnel command)
    (let* ((name (ssh-tunnels--property tunnel :name))
         (tunnel-type (ssh-tunnels--property tunnel :type))
         (login (ssh-tunnels--property tunnel :login))
         (args
...
```

I can spend few hours on it if it may be an interesting feature.

**Comment by death** [comment]
It's fine as it is; you just need to build the right list structure. For example, you can use backquote: `` `((:name ... :host ,ahost ...))``.

**Comment by texaco** [comment]
Awesome! Didn't know this feature. Thanks!
