### ISSUE TITLE
Allow for other tunnel types

### ISSUE THREAD

**Issue by evilham** [death/ssh-tunnels#5]
I think this is related to #4 #3 albeit, I treated it more generically and actually did the thing:

* Added a `type` property to tunnels, that defaults to `-L` and accepts `-D` or `-R`
* If `-D`, `RPort` is optional and any setup value is ignored
* Its value is listed on `ssh-tunnels` table

If there is a chance of merging this and publishing to elpa, please reply and I'll add the documentation strings and create a Merge Request.

**Comment by death** [comment]
Sure, go ahead.
